# Install script for directory: C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/opencv/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "licenses" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE OPTIONAL RENAME "ade-LICENSE" FILES "C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/3rdparty/ade/ade-0.1.1d/LICENSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/calib3d/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/core/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/dnn/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/features2d/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/flann/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/gapi/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/highgui/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/imgproc/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/java/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/js/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/ml/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/objdetect/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/photo/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/python/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/stitching/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/ts/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/video/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/videoio/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/.firstpass/world/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/core/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/flann/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/imgproc/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/java_bindings_generator/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/ml/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/photo/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/dnn/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/gapi/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/imgcodecs/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/videoio/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/highgui/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/ts/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/features2d/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/calib3d/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/objdetect/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/stitching/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/video/cmake_install.cmake")
  include("C:/Users/Tomas/Documents/GitHub/491/panorama/opencv_build/final/modules/python_bindings_generator/cmake_install.cmake")

endif()

